<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container27tjrmV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container27tjrmV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container27tjrmV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container27tjrmV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container27tjrmV\App_KernelDevDebugContainer([
    'container.build_hash' => '27tjrmV',
    'container.build_id' => '2e570122',
    'container.build_time' => 1654534691,
], __DIR__.\DIRECTORY_SEPARATOR.'Container27tjrmV');
